--
-- PostgreSQL database dump
--

-- Dumped from database version 16.2
-- Dumped by pg_dump version 16.2

-- Started on 2024-06-19 10:52:39

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 5098 (class 0 OID 35021)
-- Dependencies: 287
-- Data for Name: mt_status_pengajuan_penerima; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (1, 1, 10, 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 4);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (2, 2, 11, 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 15, 4);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (3, 3, 13, 4, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 15, 4);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (4, 4, 2, 5, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 15, 4);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (5, 6, 10, 7, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 4);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (6, 7, 11, 8, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 16, 4);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (7, 8, 13, 9, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 16, 4);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (8, 9, 2, 10, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 16, 4);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (13, 11, 10, 12, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 4);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (14, 12, 11, 13, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 17, 4);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (15, 13, 13, 14, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 17, 4);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (16, 14, 2, 10, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 17, 4);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (17, 1, 10, 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 3);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (19, 4, 2, 5, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 15, 3);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (20, 6, 10, 7, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 3);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (22, 9, 2, 10, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 16, 3);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (23, 11, 10, 12, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 3);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (25, 14, 2, 10, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 17, 3);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (26, 1, 10, 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 2);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (27, 2, 11, 4, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 15, 2);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (28, 4, 2, 5, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 15, 2);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (29, 6, 10, 7, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 2);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (30, 7, 11, 9, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 16, 2);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (31, 9, 2, 10, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 16, 2);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (32, 11, 10, 12, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 2);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (33, 12, 11, 14, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 17, 2);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (34, 14, 2, 10, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 17, 2);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (318, 1, 10, 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 7);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (319, 2, 11, 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 15, 7);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (320, 3, 13, 4, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 15, 7);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (321, 4, 2, 5, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 15, 7);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (322, 6, 10, 7, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 7);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (323, 7, 11, 8, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 16, 7);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (324, 8, 13, 9, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 16, 7);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (325, 9, 2, 10, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 16, 7);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (326, 11, 10, 12, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 7);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (327, 12, 11, 13, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 17, 7);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (328, 13, 13, 14, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 17, 7);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (329, 14, 2, 10, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 17, 7);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (330, 1, 10, 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 11);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (332, 4, 2, 5, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 15, 11);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (333, 6, 10, 7, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 11);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (334, 7, 11, 9, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 16, 11);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (335, 9, 2, 10, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 16, 11);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (336, 11, 10, 12, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 11);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (337, 12, 11, 14, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 17, 11);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (338, 14, 2, 10, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 17, 11);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (381, 1, 1, 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 11);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (383, 4, 1, 5, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 15, 11);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (384, 6, 1, 7, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 11);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (385, 7, 1, 9, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 16, 11);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (386, 9, 1, 10, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 16, 11);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (387, 11, 1, 12, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 11);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (388, 12, 1, 14, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 17, 11);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (389, 14, 1, 10, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 17, 11);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (390, 1, 1, 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (391, 2, 1, 4, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 15, 1);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (392, 4, 1, 5, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 15, 1);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (393, 6, 1, 7, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (394, 7, 1, 9, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 16, 1);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (395, 9, 1, 10, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 16, 1);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (396, 11, 1, 12, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (397, 12, 1, 14, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 17, 1);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (398, 14, 1, 10, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 17, 1);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (399, 1, 1, 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 10);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (401, 4, 1, 5, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 15, 10);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (402, 6, 1, 7, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 10);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (403, 9, 1, 10, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 16, 10);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (404, 11, 1, 12, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 10);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (405, 14, 1, 10, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 17, 10);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (406, 1, 1, 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 5);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (331, 2, 11, 4, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 15, 11);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (400, 2, 1, 4, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 15, 10);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (18, 2, 11, 4, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 15, 3);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (115, 2, 11, 4, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 15, 10);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (133, 2, 11, 4, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 15, 5);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (21, 7, 11, 9, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 16, 3);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (380, 12, 1, 14, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 17, 3);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (105, 1, 10, 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (106, 2, 11, 4, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 15, 1);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (107, 4, 2, 5, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 15, 1);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (108, 6, 10, 7, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (109, 7, 11, 9, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 16, 1);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (110, 9, 2, 10, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 16, 1);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (111, 11, 10, 12, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (112, 12, 11, 14, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 17, 1);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (113, 14, 2, 10, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 17, 1);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (114, 1, 10, 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 10);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (116, 4, 2, 5, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 15, 10);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (117, 6, 10, 7, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 10);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (119, 9, 2, 10, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 16, 10);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (120, 11, 10, 12, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 10);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (122, 14, 2, 10, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 17, 10);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (132, 1, 10, 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 5);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (118, 7, 11, 9, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 16, 10);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (121, 12, 11, 14, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 17, 10);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (135, 4, 2, 5, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 15, 5);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (136, 6, 10, 7, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 5);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (139, 9, 2, 10, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 16, 5);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (140, 11, 10, 12, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 5);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (143, 14, 2, 10, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 17, 5);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (144, 1, 10, 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 6);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (145, 2, 11, 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 15, 6);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (146, 3, 13, 4, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 15, 6);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (147, 4, 2, 5, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 15, 6);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (148, 6, 10, 7, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 6);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (149, 7, 11, 8, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 16, 6);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (150, 8, 13, 9, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 16, 6);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (151, 9, 2, 10, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 16, 6);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (152, 11, 10, 12, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 6);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (153, 12, 11, 13, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 17, 6);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (154, 13, 13, 14, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 17, 6);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (155, 14, 2, 10, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 17, 6);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (158, 3, 13, 4, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 15, 4);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (168, 1, 10, 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 8);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (169, 2, 11, 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 15, 8);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (170, 3, 13, 4, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 15, 8);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (171, 4, 2, 5, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 15, 8);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (172, 6, 10, 7, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 8);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (173, 7, 11, 8, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 16, 8);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (174, 8, 13, 9, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 16, 8);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (175, 9, 2, 10, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 16, 8);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (176, 11, 10, 12, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 8);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (177, 12, 11, 13, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 17, 8);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (178, 13, 13, 14, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 17, 8);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (179, 14, 2, 10, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 17, 8);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (180, 1, 10, 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 9);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (181, 2, 11, 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 15, 9);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (182, 3, 13, 4, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 15, 9);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (183, 4, 2, 5, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 15, 9);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (184, 6, 10, 7, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 9);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (185, 7, 11, 8, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 16, 9);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (186, 8, 13, 9, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 16, 9);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (187, 9, 2, 10, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 16, 9);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (188, 11, 10, 12, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 9);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (189, 12, 11, 13, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 17, 9);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (190, 13, 13, 14, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 17, 9);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (191, 14, 2, 10, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 17, 9);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (339, 1, 1, 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 4);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (340, 2, 1, 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 15, 4);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (341, 3, 1, 4, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 15, 4);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (342, 4, 1, 5, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 15, 4);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (343, 6, 1, 7, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 4);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (344, 7, 1, 8, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 16, 4);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (345, 8, 1, 9, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 16, 4);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (346, 9, 1, 10, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 16, 4);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (347, 11, 1, 12, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 4);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (348, 12, 1, 13, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 17, 4);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (349, 13, 1, 14, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 17, 4);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (350, 14, 1, 10, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 17, 4);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (351, 1, 1, 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 3);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (352, 4, 1, 5, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 15, 3);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (353, 6, 1, 7, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 3);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (354, 9, 1, 10, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 16, 3);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (355, 11, 1, 12, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 3);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (356, 14, 1, 10, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 17, 3);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (357, 1, 1, 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 2);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (358, 2, 1, 4, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 15, 2);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (359, 4, 1, 5, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 15, 2);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (360, 6, 1, 7, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 2);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (361, 7, 1, 9, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 16, 2);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (362, 9, 1, 10, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 16, 2);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (363, 11, 1, 12, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 2);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (364, 12, 1, 14, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 17, 2);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (365, 14, 1, 10, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 17, 2);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (366, 1, 1, 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 7);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (367, 2, 1, 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 15, 7);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (368, 3, 1, 4, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 15, 7);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (369, 4, 1, 5, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 15, 7);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (370, 6, 1, 7, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 7);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (371, 7, 1, 8, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 16, 7);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (372, 8, 1, 9, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 16, 7);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (373, 9, 1, 10, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 16, 7);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (374, 11, 1, 12, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 7);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (375, 12, 1, 13, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 17, 7);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (376, 13, 1, 14, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 17, 7);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (377, 14, 1, 10, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 17, 7);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (378, 2, 1, 4, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 15, 3);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (137, 7, 11, 9, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 16, 5);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (141, 12, 11, 14, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 17, 5);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (379, 7, 1, 9, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 16, 3);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (408, 7, 1, 9, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 16, 10);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (409, 12, 1, 14, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 17, 10);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (411, 4, 1, 5, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 15, 5);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (412, 6, 1, 7, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 5);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (415, 9, 1, 10, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 16, 5);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (416, 11, 1, 12, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 5);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (419, 14, 1, 10, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 17, 5);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (420, 1, 1, 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 6);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (421, 2, 1, 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 15, 6);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (422, 3, 1, 4, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 15, 6);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (423, 4, 1, 5, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 15, 6);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (424, 6, 1, 7, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 6);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (425, 7, 1, 8, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 16, 6);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (426, 8, 1, 9, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 16, 6);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (427, 9, 1, 10, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 16, 6);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (428, 11, 1, 12, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 6);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (429, 12, 1, 13, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 17, 6);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (430, 13, 1, 14, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 17, 6);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (431, 14, 1, 10, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 17, 6);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (432, 3, 1, 4, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 15, 4);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (433, 1, 1, 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 8);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (434, 2, 1, 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 15, 8);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (435, 3, 1, 4, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 15, 8);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (436, 4, 1, 5, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 15, 8);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (437, 6, 1, 7, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 8);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (438, 7, 1, 8, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 16, 8);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (439, 8, 1, 9, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 16, 8);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (440, 9, 1, 10, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 16, 8);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (441, 11, 1, 12, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 8);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (442, 12, 1, 13, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 17, 8);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (443, 13, 1, 14, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 17, 8);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (444, 14, 1, 10, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 17, 8);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (445, 1, 1, 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 9);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (446, 2, 1, 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 15, 9);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (447, 3, 1, 4, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 15, 9);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (448, 4, 1, 5, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 15, 9);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (449, 6, 1, 7, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 9);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (450, 7, 1, 8, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 16, 9);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (451, 8, 1, 9, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 16, 9);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (452, 9, 1, 10, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 16, 9);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (453, 11, 1, 12, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 9);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (454, 12, 1, 13, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 17, 9);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (455, 13, 1, 14, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 17, 9);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (456, 14, 1, 10, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 17, 9);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (382, 2, 1, 4, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 15, 11);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (407, 2, 1, 4, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 15, 5);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (413, 7, 1, 9, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 16, 5);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (417, 12, 1, 14, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 17, 5);
INSERT INTO public.mt_status_pengajuan_penerima (id_status_pengajuan_penerima, id_status_pengajuan, id_group, id_status_pengajuan_selanjutnya, created_at, updated_at, created_by, updated_by, deleted_by, deleted_at, created_by_desc, updated_by_desc, deleted_by_desc, id_status_pengajuan_dikembalikan, id_assessment_type) VALUES (24, 12, 11, 14, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 17, 3);


--
-- TOC entry 5105 (class 0 OID 0)
-- Dependencies: 288
-- Name: mt_status_pengajuan_penerima_id_status_pengajuan_penerima_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.mt_status_pengajuan_penerima_id_status_pengajuan_penerima_seq', 456, true);


-- Completed on 2024-06-19 10:52:39

--
-- PostgreSQL database dump complete
--

