SELECT
	A.*,
	MRM.ID_TINGKAT AS ID_TINGKAT_INHEREN,
	MRM.SKALA AS SKALA_INHEREN,
	MRMT.ID_TINGKAT AS ID_TINGKAT_TARGET,
	MRMT.SKALA AS SKALA_TARGET,
	MRMR.ID_TINGKAT AS ID_TINGKAT_REAL,
	MRMR.SKALA AS SKALA_REAL
FROM
	(
		SELECT
		id_kriteria_dampak,
		ID_RISK_AGREGASI_RISIKO,
			A.JENIS,
			A.NAMA,
			IS_KUANTITATIF,
			CASE
				WHEN IS_KUANTITATIF = 0
				OR IS_KUANTITATIF IS NULL THEN A.ID_DAMPAK_KUALITATIF_INHEREN
				ELSE MRD.ID_DAMPAK
			END AS ID_DAMPAK_INHEREN,
			CASE
				WHEN IS_KUANTITATIF = 0
				OR IS_KUANTITATIF IS NULL THEN NULL
				ELSE A.NILAI_DAMPAK_INHEREN
			END AS NILAI_DAMPAK_INHEREN,
			A.NILAI_KEMUNGKINAN_INHEREN,
			MRK.ID_KEMUNGKINAN AS ID_KEMUNGKINAN_INHEREN,
			CASE
				WHEN IS_KUANTITATIF = 0
				OR IS_KUANTITATIF IS NULL THEN NULL
				ELSE A.NILAI_EKSPOSUR_INHEREN
			END AS NILAI_EKSPOSUR_INHEREN,
			CASE
				WHEN IS_KUANTITATIF = 0
				OR IS_KUANTITATIF IS NULL THEN A.ID_DAMPAK_KUALITATIF_TARGET
				ELSE MRDT.ID_DAMPAK
			END AS ID_DAMPAK_TARGET,
			CASE
				WHEN IS_KUANTITATIF = 0
				OR IS_KUANTITATIF IS NULL THEN NULL
				ELSE A.NILAI_DAMPAK_TARGET
			END AS NILAI_DAMPAK_TARGET,
			A.NILAI_KEMUNGKINAN_TARGET,
			MRKT.ID_KEMUNGKINAN AS ID_KEMUNGKINAN_TARGET,
			CASE
				WHEN IS_KUANTITATIF = 0
				OR IS_KUANTITATIF IS NULL THEN NULL
				ELSE A.NILAI_EKSPOSUR_TARGET
			END AS NILAI_EKSPOSUR_TARGET,
			CASE
				WHEN IS_KUANTITATIF = 0
				OR IS_KUANTITATIF IS NULL THEN A.ID_DAMPAK_KUALITATIF_REAL
				ELSE MRDR.ID_DAMPAK
			END AS ID_DAMPAK_REAL,
			CASE
				WHEN IS_KUANTITATIF = 0
				OR IS_KUANTITATIF IS NULL THEN NULL
				ELSE A.NILAI_DAMPAK_REAL
			END AS NILAI_DAMPAK_REAL,
			A.NILAI_KEMUNGKINAN_REAL,
			MRKR.ID_KEMUNGKINAN AS ID_KEMUNGKINAN_REAL,
			CASE
				WHEN IS_KUANTITATIF = 0
				OR IS_KUANTITATIF IS NULL THEN NULL
				ELSE A.NILAI_EKSPOSUR_REAL
			END AS NILAI_EKSPOSUR_REAL
		FROM
			(
				SELECT
					MRA.NAMA,
					RP.*,
					MRAS.NILAI_SASARAN,
					RP.NILAI_DAMPAK_INHEREN / MRAS.NILAI_SASARAN * 100 AS PERSEN_DAMPAK_INHEREN,
					RP.NILAI_DAMPAK_TARGET / MRAS.NILAI_SASARAN * 100 AS PERSEN_DAMPAK_TARGET,
					RP.NILAI_DAMPAK_REAL / MRAS.NILAI_SASARAN * 100 AS PERSEN_DAMPAK_REAL
				FROM
					(
						SELECT
							RP.JENIS,
							TO_CHAR(RP.TGL_RISIKO, 'YYYY')::INT TAHUN,
							IS_KUANTITATIF,
							RP.ID_RISK_AGREGASI_RISIKO,
						rp.id_kriteria_dampak,
							SUM(RP.NILAI_DAMPAK_INHEREN) AS NILAI_DAMPAK_INHEREN,
							CASE
								WHEN IS_KUANTITATIF = 0
								OR IS_KUANTITATIF IS NULL THEN AVG(RP.NILAI_KEMUNGKINAN)
								ELSE ROUND(
									SUM(
										RP.NILAI_DAMPAK_INHEREN * RP.NILAI_KEMUNGKINAN / 100
									) / SUM(RP.NILAI_DAMPAK_INHEREN) * 100
								)
							END AS NILAI_KEMUNGKINAN_INHEREN,
							SUM(
								RP.NILAI_DAMPAK_INHEREN * RP.NILAI_KEMUNGKINAN / 100
							) AS NILAI_EKSPOSUR_INHEREN,
							FLOOR(AVG(RP.ID_DAMPAK_INHEREN)) AS ID_DAMPAK_KUALITATIF_INHEREN,
							SUM(RPTS.NILAI_DAMPAK) AS NILAI_DAMPAK_TARGET,
							CASE
								WHEN IS_KUANTITATIF = 0
								OR IS_KUANTITATIF IS NULL THEN AVG(RPTS.NILAI_KEMUNGKINAN)
								ELSE ROUND(
									SUM(RPTS.NILAI_DAMPAK * RPTS.NILAI_KEMUNGKINAN / 100) / SUM(RPTS.NILAI_DAMPAK) * 100
								)
							END AS NILAI_KEMUNGKINAN_TARGET,
							SUM(RPTS.NILAI_DAMPAK * RPTS.NILAI_KEMUNGKINAN / 100) AS NILAI_EKSPOSUR_TARGET,
							FLOOR(AVG(RPTS.ID_DAMPAK)) AS ID_DAMPAK_KUALITATIF_TARGET,
							SUM(RPRR.NILAI_DAMPAK) AS NILAI_DAMPAK_REAL,
							CASE
								WHEN IS_KUANTITATIF = 0
								OR IS_KUANTITATIF IS NULL THEN AVG(RPRR.NILAI_KEMUNGKINAN)
								ELSE ROUND(
									SUM(RPRR.NILAI_DAMPAK * RPRR.NILAI_KEMUNGKINAN / 100) / SUM(RPTS.NILAI_DAMPAK) * 100
								)
							END AS NILAI_KEMUNGKINAN_REAL,
							SUM(RPRR.NILAI_DAMPAK * RPRR.NILAI_KEMUNGKINAN / 100) AS NILAI_EKSPOSUR_REAL,
							FLOOR(AVG(RPRR.ID_DAMPAK)) AS ID_DAMPAK_KUALITATIF_REAL
						FROM
							RISK_PROFILE RP
							LEFT JOIN RISK_PROFILE_TARGET_RESIDUAL RPTS ON RP.ID_RISK_PROFILE = RPTS.ID_RISK_PROFILE
							AND RPTS.PERIODE = '2024q2'
							LEFT JOIN RISK_PROFILE_REALISASI_RESIDUAL RPRR ON RP.ID_RISK_PROFILE = RPRR.ID_RISK_PROFILE
							AND RPRR.PERIODE = '20243'
						GROUP BY
							JENIS,
						rp.id_kriteria_dampak,
							ID_RISK_AGREGASI_RISIKO,
							IS_KUANTITATIF,
							TO_CHAR(RP.TGL_RISIKO, 'YYYY')
					) RP
					JOIN MT_RISK_AGREGASI_RISIKO MRA ON RP.ID_RISK_AGREGASI_RISIKO = MRA.ID_RISK_AGREGASI_RISIKO
					LEFT JOIN MT_RISK_AGREGASI_RISIKO_SASARAN MRAS ON MRA.ID_RISK_AGREGASI_RISIKO = MRAS.ID_RISK_AGREGASI_RISIKO
					AND MRAS.TAHUN = RP.TAHUN
			) A
			JOIN MT_RISK_DAMPAK MRD ON (
				PERSEN_DAMPAK_INHEREN >= MRD.MULAI
				OR MRD.ID_DAMPAK = 1
			)
			AND (
				PERSEN_DAMPAK_INHEREN < MRD.SAMPAI
				OR MRD.ID_DAMPAK = 5
			)
			JOIN MT_RISK_KEMUNGKINAN MRK ON (
				NILAI_KEMUNGKINAN_INHEREN >= MRK.PERSENTASE_MULAI
				OR MRK.ID_KEMUNGKINAN = 1
			)
			AND (
				NILAI_KEMUNGKINAN_INHEREN < MRK.PERSENTASE_SAMPAI
				OR MRK.ID_KEMUNGKINAN = 5
			)
			JOIN MT_RISK_DAMPAK MRDT ON (
				PERSEN_DAMPAK_TARGET >= MRDT.MULAI
				OR MRDT.ID_DAMPAK = 1
			)
			AND (
				PERSEN_DAMPAK_TARGET < MRDT.SAMPAI
				OR MRDT.ID_DAMPAK = 5
			)
			JOIN MT_RISK_KEMUNGKINAN MRKT ON (
				NILAI_KEMUNGKINAN_TARGET >= MRKT.PERSENTASE_MULAI
				OR MRKT.ID_KEMUNGKINAN = 1
			)
			AND (
				NILAI_KEMUNGKINAN_TARGET < MRKT.PERSENTASE_SAMPAI
				OR MRKT.ID_KEMUNGKINAN = 5
			)
			JOIN MT_RISK_DAMPAK MRDR ON (
				PERSEN_DAMPAK_REAL >= MRDR.MULAI
				OR MRDR.ID_DAMPAK = 1
			)
			AND (
				PERSEN_DAMPAK_REAL < MRDR.SAMPAI
				OR MRDR.ID_DAMPAK = 5
			)
			JOIN MT_RISK_KEMUNGKINAN MRKR ON (
				NILAI_KEMUNGKINAN_REAL >= MRKR.PERSENTASE_MULAI
				OR MRKR.ID_KEMUNGKINAN = 1
			)
			AND (
				NILAI_KEMUNGKINAN_REAL < MRKR.PERSENTASE_SAMPAI
				OR MRKR.ID_KEMUNGKINAN = 5
			)
	) A
	JOIN MT_RISK_MATRIX MRM ON A.ID_DAMPAK_INHEREN = MRM.ID_DAMPAK
	AND A.ID_KEMUNGKINAN_INHEREN = MRM.ID_KEMUNGKINAN
	AND A.JENIS = MRM.JENIS
	JOIN MT_RISK_MATRIX MRMT ON A.ID_DAMPAK_TARGET = MRMT.ID_DAMPAK
	AND A.ID_KEMUNGKINAN_TARGET = MRMT.ID_KEMUNGKINAN
	AND A.JENIS = MRMT.JENIS
	JOIN MT_RISK_MATRIX MRMR ON A.ID_DAMPAK_REAL = MRMR.ID_DAMPAK
	AND A.ID_KEMUNGKINAN_REAL = MRMR.ID_KEMUNGKINAN
	AND A.JENIS = MRMR.JENIS
ORDER BY
	SKALA_INHEREN DESC;